version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: distcomp
    ports:
      - "5432:5432"
    restart: unless-stopped