spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: 'DC'
  cassandra:
    keyspace-name: publicator
    contact-points: localhost:9042
    username: cassandra
    password: cassandra
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
server:
  port: 24110
springdoc:
  api-docs:
    enabled: true
    path: /api/v1.0/docs
  swagger-ui:
    path: /api/v1.0/ui-docs.html